### ISSUE TITLE
found too many digits (7)

### ISSUE THREAD

**Issue by AIGirl10** [auerswal/ssocr#13]
Tried to implement the given example, with given image [here](https://www.unix-ag.uni-kl.de/~auerswal/ssocr/index.html).

but when try to implement it, its giving this error
```sh
found too many digits (6)
```

but there are only 6 digits in the image. Can anyone please help ? thanks

**Comment by auerswal** [comment]
Hi @AIGirl10,

I have two images on that web site with example `ssocr` command lines, [six_digits.png](https://www.unix-ag.uni-kl.de/~auerswal/ssocr/six_digits.png) and [inside_box.png](https://www.unix-ag.uni-kl.de/~auerswal/ssocr/inside_box.png), and both examples work for me:

```
$ rm -f six_digits.png && wget -q https://www.unix-ag.uni-kl.de/~auerswal/ssocr/six_digits.png && ssocr -T six_digits.png 
431432
$ rm -f inside_box.png && wget -q https://www.unix-ag.uni-kl.de/~auerswal/ssocr/inside_box.png && ssocr crop 230 195 220 60 -t 20 inside_box.png
086861
```

There is a third image on my web site used to illustrate the algorithm that is *produced* with ssocr, but cannot be recognized by it: [illustrate_algo.png](https://www.unix-ag.uni-kl.de/~auerswal/ssocr/illustrate_algo.png). This image can be created as follows:

```
$ ls illustrate_algo.png
ls: cannot access 'illustrate_algo.png': No such file or directory
$ ssocr -Dillustrate_algo.png -T -v six_digits.png 
loading image six_digits.png
using threshold 81.37
no commands given, using image six_digits.png unmodified
431432
using png format for debug image
writing debug image to file illustrate_algo.png
$ ls illustrate_algo.png
illustrate_algo.png
```

Trying to reproduce this example without `-T` does not work:

```
$ ssocr -D six_digits.png 
found too many digits (7)
```

Did you mean this with your question? I have just updated my web page to show the full command line required.

HTH,
Erik

**Comment by AIGirl10** [comment]
@auerswal 

Thankss, -T gave perfect results :)
