### ISSUE TITLE
Is there a way to specify negative rotation values?

### ISSUE THREAD

**Issue by chconnor** [auerswal/ssocr#24]
If I want to rotate -2.2 degrees, I currently rotate 357.8 instead, because -2.2 gets interpreted as an (unknown) option. I've tried \-2.2 and \\-2.2 to no avail. Anyway to specify negative values?

No big deal, just thought I'd ask if there was something obvious I was missing. :-)

**Comment by auerswal** [comment]
Yes, specifying negative values to commands is possible. You need to specify the command after all options, and use the special `getopt_long()` argument `--` that terminates option processing after the last option and before the non-option argument starting with a minus (hyphen), e.g.:

```
ssocr -T -- rotate -2.2 image.png
```

The `--` works without any real options, too. It can even be given between the command and its argument (but that looks odd):

```
ssocr -- rotate -2.2 image.png
ssocr rotate -- -2.2 image.png
```

This is part of the GNU `getopt_long()` implementation, not part of `ssocr` itself.
