### ISSUE TITLE
Wrong detection of 13 (detected as 8)

### ISSUE THREAD

**Issue by maxux** [auerswal/ssocr#25]
Hey, I try to use `ssocr` to get real time monitoring of a battery which only have status display. I could get expected data but I hit an tricky case for a `0013` detected as `008`. Is there any specific option to workaround this ?

Here is the full image:
![2024-05-07-201625](https://github.com/auerswal/ssocr/assets/4141584/e3714f3b-778f-4d8d-9bc0-4d2756be2b84)

Here is the debug cropped zone:
![testbild](https://github.com/auerswal/ssocr/assets/4141584/1679d888-1f09-42f3-8a86-2317a506f22e)

The command executed:
```
./ssocr -f white -b black -d 4 -D crop 571 229 178 76 /tmp/2024-05-07-201625.png
```

Any tips are welcome, thanks ! :)

**Comment by auerswal** [comment]
You just need to crop away all image parts that do not show a single line of seven segment displays. The following works for this number from your image:

```
$ ssocr -f white -d 4 crop 571 235 140 55 issue25.png 
0013
```

For an image like this with many numbers, each shown with an individual group of seven segment displays, you need one `ssocr` invocation per number (i.e., per group of related seven segment displays).

**Comment by maxux** [comment]
Thanks, this works quite well on a large set of data ! With `< 1%` error, perfect, thanks a lot !
