### ISSUE TITLE
notdebian/*

### ISSUE THREAD

**Issue by alexmyczko** [auerswal/ssocr#27]
I guess it would be safe and good to get rid of this directory including all contents?

an updated version is findable at https://sources.debian.org/src/ssocr/2.23.1-1/debian/
for example.

**Comment by auerswal** [comment]
Why? What is the problem? Please elaborate.

**Comment by alexmyczko** [comment]
What would it be good for? It is not up to date, it is not likely to work anymore, unless you dig out 10 year old debian system and build it from there?

**Comment by auerswal** [comment]
It still builds a `.deb` package on at least Debian stable, Debian old-stable, and the Ubuntu LTS I checked.
