### ISSUE TITLE
How should I integrate this library with android 

### ISSUE THREAD

**Issue by pawarn** [auerswal/ssocr#8]
I am working on Healthcare project where I want to read data from different devices using a mobile camera. Like HB meter.

So how should I use this with android?

**Comment by auerswal** [comment]
Well, it seems as if some POSIX compatible software can be compiled and used with Android. This may provide an avenue for `ssocr` on Android.

But a mobile phone or tablet does not provide a Unix-like user interface. You would probably need to write a completely different frontend that uses the camera view to select which image to send to `ssocr`. The flash LED might be of use in low-light situations.

A mobile phone resp. tablet UI might more or less *continuously* invoke `ssocr` on the currently viewed image and display the recognized value next to the camera image.

Anyway, that would be a significant undertaking as opposed to just *using* `ssocr` (a program for use on a Unix-like system) on Android (which is not Unix-like at all, despite using a fork of the Unix-like kernel Linux). The same holds for iOS (based on a fork of the Unix(-like) FreeBSD kernel with a non-Unix-like UI on top).
