### ISSUE TITLE
Unclear homebrew installation instructions

### ISSUE THREAD

**Issue by sgronblo** [auerswal/ssocr#9]
The ssocr web site at https://www.unix-ag.uni-kl.de/~auerswal/ssocr/ mentions that:

> Mac OS X (using Homebrew to install Imlib2)

I found a package called `imlib2` and installed it using homebrew. But it did not seem to add a binary called `ssocr` anywhere on my PATH.

**Comment by sgronblo** [comment]
On reading the site more closely I think I misunderstood. I guess these instructions are saying that you can build ssocr by yourself by installing imlib2 through homebrew?

**Comment by auerswal** [comment]
Yes, the Imlib2 library is needed to build `ssocr`. For macOS (I think that is the current name for Mac OS X), Imlib2 is available via Homebrew, I have been told (I do not have a Mac).

After installing Imlib2 on macOS, one can download the `ssocr` sources and build them. This requires a build environment including a C compiler on the Mac as well.

I have reworded the macOS part of the homepage:

> Mac OS X (the required library Imlib2 can be installed via Homebrew)

I hope that helps. :-)

Thanks,
Erik

**Comment by sgronblo** [comment]
Yeah, thanks. I was able to build it with no problem.
